extract_template_fields:
  description: >
    Visit {link} and return the field schema needed to create the application
    documentation according to the TechOps template. If {link} has an anchor,
    restrict the output to that section.
  expected_output: >
    A JSON object with: "template", "sections":[...]
  agent: web_search_agent

generate_ethics_doc:
  description: >
    Create a TechOps-style ethics documentation for {app_name} in HTML in the Italian language using the
    section/field schema provided via the task context and the Sphinx documentation
    analyzed through rag_tool_sphinx. Preserve the template structure, cite sources per
    section, and add a final "Missing Information (To Ask the User)" section.
  agent: docs_agent
  context:
    - extract_template_fields   # prior task that outputs the schema; becomes this task's context
  expected_output: >
    A single, self-contained HTML document that follows the schema order from context,
    fills each field using ONLY Sphinx-derived information (or marks it as
    "<em>Not available in the provided context.</em>"), cites Sphinx sources by basename,
    and includes a final "Missing Information (To Ask the User)" section.
  output_file: output/{app_name_slug}_techops.html
